### ISSUE TITLE
Your website is not viewable

### ISSUE THREAD

**Issue by zoraezimran** [xItzDiamondx/home#1]
I cannot see your website page when i click on the link. ==> https://xitzdiamondx.github.io/home/

All it says is 404 Page cannot be found

**Comment by xItzDiamondx** [comment]
Yes. I am aware of that.

**Comment by xItzDiamondx** [comment]
Ah, it was the wrong URL. Try this ➣ xitzdiamondx.github.io/website/

**Comment by zoraezimran** [comment]
ok
